<?php
Package::setList([
	'account' => 'accounting',
	'analyze' => 'ouvretaferme',
	'asset' => 'accounting',
	'association' => 'ouvretaferme',
	'bank' => 'accounting',
	'cash' => 'accounting',
	'company' => 'accounting',
	'core' => 'framework',
	'data' => 'base',
	'dev' => 'framework',
	'editor' => 'framework',
	'example' => 'framework',
	'farm' => 'base',
	'gallery' => 'production',
	'game' => 'ouvretaferme',
	'hr' => 'base',
	'invoicing' => 'accounting',
	'journal' => 'accounting',
	'language' => 'framework',
	'mail' => 'base',
	'main' => 'ouvretaferme',
	'map' => 'production',
	'media' => 'base',
	'overview' => 'accounting',
	'payment' => 'commercialisation',
	'pdp' => 'accounting',
	'plant' => 'production',
	'preaccounting' => 'accounting',
	'securing' => 'base',
	'selling' => 'commercialisation',
	'sequence' => 'production',
	'series' => 'production',
	'session' => 'framework',
	'shop' => 'commercialisation',
	'storage' => 'framework',
	'user' => 'framework',
	'util' => 'framework',
	'vat' => 'accounting',
	'website' => 'ouvretaferme',
]);

Package::setObservers([
	'lib' => [
		'shop' => [
			'salePaid' => ['association', 'shop'],
			'saleFailed' => ['association', 'shop'],
			'saleConfirmed' => ['shop'],
			'saleUpdated' => ['shop'],
			'saleCanceled' => ['shop'],
		],
		'data' => [
			'calculateFarmData' => ['company'],
		],
		'user' => [
			'logIn' => ['company', 'farm', 'session'],
			'formLog' => ['company', 'farm'],
			'formSignUp' => ['company', 'farm'],
			'canUpdate' => ['main'],
			'sendVerifyEmail' => ['main'],
			'signUpCreate' => ['main', 'selling'],
			'close' => ['main'],
			'checkElectronicAddress' => ['pdp'],
			'getCountrySchemes' => ['pdp'],
			'update' => ['selling'],
			'logOut' => ['session'],
		],
		'lime' => [
			'loadConf' => ['media'],
		],
	],
	'ui' => [
		'user' => [
			'signUpForm' => ['main'],
			'emailSignUp' => ['main'],
		],
	],
]);
?>
